void Map(int pole[10][10]);
void Spawn(int pole[10][10], int x , int y, int s_long);
void menu();
void How_to_Play();
void Set_Ships();
void Add_Ship(int s_long);
void Type();
void Computer_Ships();
void Computer_Spawn(int plansza[10][10], int dl);
void Save_Computer(int plansza[10][10]);
void Delete_Files();
void Player_Ships();
void Player_Spawn(int plansza[10][10], int dl);
void Save_Player(int plansza[10][10]);
void See_Files();
void Game();
void Player_move(char tab[10][10], bool wynik);
void Computer_move(char tab[10][10], bool wynik);